### ISSUE TITLE
Class defined at the top of the feature files is ignored

### ISSUE THREAD

**Issue by mathieureguer** [typemytype/featurePreviewRoboFontExtension#10]
There seems to be an issue when classes are declared at the top of a feature file.
Consider the following feature code:

```
@test_off = [a b c];
@test_on = [A B C];

feature ss01 {
    sub @test_off by @test_on;
} ss01;
```

The first class on the first line seems to be consistently ignored by the compiler. `@test_off` is flagged as not defined.
Adding a blank line at the top of the screen does not fix the issue. Starting with a comment does resolves it.

```
# dummy line

@test_off = [a b c];
@test_on = [A B C];

feature ss01 {
    sub @test_off by @test_on;
} ss01;
```

No big deal but I though I should mention it.
(Feature Preview is great. Glad to see it gets some Harfbuzz love).

**Comment by typemytype** [comment]
please redownload from this repo and test!

thanks

**Comment by mathieureguer** [comment]
Oh no! issue persists. 😔

**Comment by typemytype** [comment]
you are sure you installed https://github.com/typemytype/featurePreviewRoboFontExtension/archive/master.zip

and you probably need to restart RF

**Comment by typemytype** [comment]
should be fixed in https://github.com/typemytype/featurePreviewRoboFontExtension/commit/29187d7316594499630bc97dece5359b96562f86

thanks!

**Comment by mathieureguer** [comment]
Fixed! Thanks!
(sorry I did not get back to you on this earlier)
