### ISSUE TITLE
Glyph preview and Glyph record don't work with new version in RF 3.3

### ISSUE THREAD

**Issue by jbmorizot** [typemytype/featurePreviewRoboFontExtension#11]
The fonts compile, the list of features appears in the FP window but when ticked, no substitutions are applied in both preview and record mode. (Features are working well in app like textEdit so no issue on this side.)

**Comment by typemytype** [comment]
is there a traceback? are you using the latest version of feature preview?

to be sure get it here directly https://github.com/typemytype/featurePreviewRoboFontExtension/archive/master.zip

what is your RF version?

**Comment by jbmorizot** [comment]
There is no traceback. RF version is 3.3 (build 1911061105). FeaturePreview is 1.2.4 updated with Mechanic2. I try with the link you gave, but it's the same one I guess, so no difference. Open binary font works pretty well though.

**Comment by typemytype** [comment]
can you provide the ufo file where it goes wrong?

**Comment by jbmorizot** [comment]
It doesn't work for all of my typefaces. It may be linked to my RF/system setup, but I don't see what could cause that. (I have a path link to ufoProcessor in external_packages folder in the  Aplication Support library, but it doesn't change anything to remove it.)

**Comment by typemytype** [comment]
should be fixed in https://github.com/typemytype/featurePreviewRoboFontExtension/commit/29187d7316594499630bc97dece5359b96562f86

thanks!

**Comment by jbmorizot** [comment]
That was fast! It works perfectly. Thanks.
