### ISSUE TITLE
can't type /glyphname anymore

### ISSUE THREAD

**Issue by cjdunn** [typemytype/featurePreviewRoboFontExtension#8]
Before this version I could type a glyphname like in space center, such as /abreveacute, but in the current version this doesn't work. This is a super handy feature for testing glyphs I don't know how to type on the keyboard or ones I can't type (ie scripts other than Latin). Thanks!

**Comment by typemytype** [comment]
I know, this behaviour is traded in for harfbuzz type setting supporting any script/language

the idea is kinda logic: input is always unicode...
and there seems not to be possible to add un-encoded glyphs to uharfbuzz....

any advice @anthrotype @behdad ?

**Comment by behdad** [comment]
What Khaled said in that linked thread.

**Comment by typemytype** [comment]
@cjdunn could you test the latest version! not yet in mechanic but directly from the repo

<img width="766" alt="Screen Shot 2019-11-08 at 00 00 41" src="https://user-images.githubusercontent.com/1190358/68435155-01dd1680-01bb-11ea-80d0-8c4289263eff.png">

**Comment by cjdunn** [comment]
Ooh cool, typing glyph names work again. Thanks!
